In [2]:
using Pkg
Pkg.add("Random")
using Random
Random.seed!(13)

  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  100.0 %.0 % Resolving package versions...
 Installed Optim ─ v0.19.7
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
  [429524aa] ↑ Optim v0.19.6 ⇒ v0.19.7


MersenneTwister(UInt32[0x0000000d], Random.DSFMT.DSFMT_state(Int32[1942364238, 1073583280, 1215809738, 1073453074, -1714420386, 1073447762, -356802344, 1073021814, -1864483401, 1072881260  …  -56294547, 1072963348, 654307797, 1073646794, 598513278, -416580782, 1018899645, 745312242, 382, 0]), [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], UInt128[0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000  …  0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x00000000000000000000000000000000, 0x000000000000

In [3]:
Pkg.add("Dates")
using Dates

 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
 [no changes]


In [4]:
using Pkg
Pkg.add("LowRankModels")
using LinearAlgebra, SparseArrays, LowRankModels
include("proxgrad.jl")

import Pkg; Pkg.add("CSV")
import Pkg; Pkg.add("Plots")
import Pkg; Pkg.add("DataFrames")
import Pkg; Pkg.add("Statistics")
import Pkg; Pkg.add("LinearAlgebra")
using CSV
using Plots
using DataFrames
using Statistics
using LinearAlgebra

 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
 [no changes]


┌ Info: Recompiling stale cache file /Users/simonng/.julia/compiled/v1.2/LowRankModels/1HEpm.ji for LowRankModels [15d4e49f-4837-5ea3-a885-5b28bfa376dc]
└ @ Base loading.jl:1240


 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
 [no changes]
 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
 [no changes]
 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
 [no changes]
 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
 [no changes]
 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
 [no changes]
 Resolving package versions...
  Updating `~/.julia/environments/v1.2/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.2/Manifest.toml`
 [no changes]


In [46]:
using StatsPlots

┌ Info: Recompiling stale cache file /Users/simonng/.julia/compiled/v1.2/StatsPlots/SiylL.ji for StatsPlots [f3b207a7-027a-5e70-b257-86293d7955fd]
└ @ Base loading.jl:1240


In [5]:
df = CSV.read("BikeWeatherZillow.csv");

### Addition of Day of the Week

In [6]:
df[!, :week_day]=dayname.(DateTime.(2018, df[:, :start_month], df[:, :start_day]));

### Deletion of Redundant Features

In [7]:
delete!(df, :start_day)
delete!(df, :start_min)
delete!(df, :start_station_latitude)
delete!(df, :start_station_longitude)
delete!(df, :start_station_zipcode);

┌ Warning: `delete!(df::AbstractDataFrame, cols::Any)` is deprecated, use `select!(df, Not(cols))` instead.
│   caller = top-level scope at In[7]:1
└ @ Core In[7]:1
┌ Warning: `delete!(df::AbstractDataFrame, cols::Any)` is deprecated, use `select!(df, Not(cols))` instead.
│   caller = top-level scope at In[7]:2
└ @ Core In[7]:2
┌ Warning: `delete!(df::AbstractDataFrame, cols::Any)` is deprecated, use `select!(df, Not(cols))` instead.
│   caller = top-level scope at In[7]:3
└ @ Core In[7]:3
┌ Warning: `delete!(df::AbstractDataFrame, cols::Any)` is deprecated, use `select!(df, Not(cols))` instead.
│   caller = top-level scope at In[7]:4
└ @ Core In[7]:4
┌ Warning: `delete!(df::AbstractDataFrame, cols::Any)` is deprecated, use `select!(df, Not(cols))` instead.
│   caller = top-level scope at In[7]:5
└ @ Core In[7]:5


We decided to now use longitude, latitude, or zipcode because it confounds with start_station_id, which is more granular than the other 2 geographic choices. 

### Casting of Types

In [8]:
df[!, :start_month]=string.(df[!, :start_month])
df[!, :start_station_id]=string.(df[!, :start_station_id])
df[!, :gender]=string.(df[!, :gender]);

In [9]:
feature_names = names(df)
for i in 1:length(feature_names)
    println(string(i), "\t", string(feature_names[i]), "\t\t\t", string(eltype(df[!, i])))
end

1	trip_duration			Int64
2	start_month			String
3	start_hour			Int64
4	start_station_id			String
5	user_type			String
6	birth_year			Int64
7	gender			String
8	total_precipitation_inches			Float64
9	average_temperature_farenheit			Float64
10	total_snowfall_inches			Float64
11	median_rental_price			String
12	median_sale_price			String
13	week_day			String


# Train/Test Split

In [10]:
df = df[shuffle(1:end), :] # we shuffle the data so that our train/test split will be truly random

train_proportion = 0.8
n = size(df, 1)
println("Size of dataset: ", string(n))

# Put the first ntrain observations in the DataFrame df into the training set, and the rest into the test set
ntrain = convert(Int, round(train_proportion*n))


target = df[:, :trip_duration]
data = df[:, filter(col -> (col != :trip_duration), feature_names)]

# the following variable records the features of examples in the training set
train_x = data[1:ntrain, :]
# the following variable records the features of examples in the test set
test_x = data[ntrain+1:end, :]
# the following variable records the labels of examples in the training set
train_y = target[1:ntrain, :]
# the following variable records the labels of examples in the test set
test_y = target[ntrain+1:end, :];

Size of dataset: 597780


# Adding Real Values to the Linear Model

In [11]:
real_labs = [
    :start_hour,
    :birth_year,
    :total_precipitation_inches,
    :average_temperature_farenheit,
    :total_snowfall_inches
]
train_vals_real = train_x[:, filter(x -> (x in real_labs), names(df))]
test_vals_real = test_x[:, filter(x -> (x in real_labs), names(df))];

## Linear Model with Only Real Values and No Transformations

In [12]:
"""This function just computes the mean squared error."""
function MSE(y, pred)
    sum = mean((y.-pred).^2)
    return sum
end;

In [13]:
Xtrain = convert(Matrix, hcat(train_vals_real, ones(length(train_vals_real[:, 1]))))
Xtest = convert(Matrix, hcat(test_vals_real, ones(length(test_vals_real[:, 1]))))

w = Xtrain \ train_y
#Xtrain \ convert(Matrix, train_y)

train_pred = Xtrain*w
test_pred = Xtest*w

train_MSE = MSE(train_y, train_pred)
test_MSE = MSE(test_y, test_pred)

println("MSE of training data: ", train_MSE)
println("MSE of test data: ", test_MSE)

MSE of training data: 2.355822827000853e8
MSE of test data: 2.0078331270520863e8


## One Hot Encoding

We used the onehot encoding function from homework 3

In [14]:
"Computes a onehot vector for every entry in column given a set of categories cats"
function onehot(column, cats=unique(column))
    result = zeros(size(column, 1),size(cats, 1))
    for i in 1:size(column, 1)
        for j in 1:(size(cats, 1))
            if(column[i]==cats[j])
                result[i,j]=1  
            end
        end
    end
    return result
end;

In [15]:
#these are the nominal categories from the CitiBike dataset.
#this doesn't include housing data because of the large amount of NAs in the data set. 
cat_labels = [
    :start_month,
    :start_station_id,
    :user_type,
    :gender,
    :week_day
]

cats_sets = [unique(train_x[:, label]) for label in cat_labels]

train_cat_vals = hcat([onehot(train_x[:, cat_labels[i]], cats_sets[i]) for i in 1:size(cat_labels, 1)]...)
test_cat_vals = hcat([onehot(test_x[:, cat_labels[i]], cats_sets[i]) for i in 1:size(cat_labels, 1)]...);

trainX = hcat(convert(Matrix, train_cat_vals), Xtrain)
testX = hcat(convert(Matrix, test_cat_vals), Xtest)

w_cat = trainX \ train_y

train_pred_cat = trainX*w_cat
test_pred_cat = testX*w_cat

cat_train_MSE = MSE(train_y, train_pred_cat)
cat_test_MSE = MSE(test_y, test_pred_cat)

println("Train MSE\t", cat_train_MSE)
println("Test MSE \t", cat_test_MSE)

Train MSE	2.333228862423659e8
Test MSE 	2.016515306066246e8


In [45]:
@df df plot(:start_hour, :trip_duration)

LoadError: UndefVarError: @df not defined

In [16]:
function toBool(y, cutoff)
    for i in 1:length(y)
        if y[i]<= cutoff
            y[i]=-1
        else
            y[i]=1
        end
    end
    return y
end

toBool (generic function with 1 method)

## Logistic Loss, Quadratic

In [17]:
#y MUST be a one dimensional vector
function logReg(x, y)
    yNew = toBool(y, 3600)
    n = length(yNew)
    loss = 1/n * LogisticLoss()
    lambda = 0.5
    reg = lambda * QuadReg()
    w = proxgrad(loss, reg, x, yNew, maxiters=1000)
    return w
end

logReg (generic function with 1 method)

## Logistic Loss with no regularization

In [18]:
#Logistic Loss with no regularization
function logReg_noreg(x, y)
    yNew = toBool(y, 3600)
    n = length(yNew)
    loss = 1/n * LogisticLoss()
    reg = ZeroReg()
    w = proxgrad(loss, reg, x, yNew, maxiters=1000)
    return w
end

logReg_noreg (generic function with 1 method)

## Logistics Loss with L1 regularization

In [19]:
function log_l1(x, y)
    yNew = toBool(y, 3600)
    n = length(yNew)
    loss = 1/n * LogisticLoss()
    reg =  OneReg()
    w = proxgrad(loss, reg, x, yNew, maxiters=10)
    return w
end

log_l1 (generic function with 1 method)

## WeightedHingeLoss with Quadratic

In [20]:
#y MUST be a one dimensional vector
function weighthingeLoss(x, y)
    yNew = toBool(y, 3600)
    n = length(yNew)
    loss = 1/n * WeightedHingeLoss()
    lambda = 0.5
    reg = lambda * QuadReg()
    w = proxgrad(loss, reg, x, yNew, maxiters=1000)
    return w
end

weighthingeLoss (generic function with 1 method)

## WeightedHingeLoss with no reg

In [21]:
# hinge loss with l1 regularization
function weighthinge_zero(x, y)
    yNew = toBool(y, 3600)
    n = length(yNew)
    loss = 1/n * WeightedHingeLoss()
    reg =  ZeroReg()
    w = proxgrad(loss, reg, x, yNew, maxiters=100)
    return w
end

weighthinge_zero (generic function with 1 method)

## Weighted Hinge Loss with lasso

In [22]:
function weighthingeLoss_lasso(x, y)
    yNew = toBool(y, 3600)
    n = length(yNew)
    loss = 1/n * WeightedHingeLoss()
    reg =  OneReg()
    w = proxgrad(loss, reg, x, yNew, maxiters=10)
    return w
end

weighthingeLoss_lasso (generic function with 1 method)

## Hinge Loss with quadratic

In [23]:
function hingeLoss(x, y)
    yNew = toBool(y, 3600)
    n = length(yNew)
    loss = 1/n * HingeLoss()
    lambda = 0.5
    reg = lambda * QuadReg()
    w = proxgrad(loss, reg, x, yNew, maxiters=1000)
    return w
end

hingeLoss (generic function with 1 method)

## Hinge Loss with no regulariation

In [24]:
# hinge loss and no regularization
function hingeLoss_noreg(x, y)
    yNew = toBool(y, 3600)
    n = length(yNew)
    loss = 1/n * HingeLoss()
    reg =  ZeroReg()
    w = proxgrad(loss, reg, x, yNew, maxiters=1000)
    return w
end

hingeLoss_noreg (generic function with 1 method)

## Hinge Loss with Lasso

In [25]:
# hinge loss and no regularization
function hingeLoss_noreg_lasso(x, y)
    yNew = toBool(y, 3600)
    n = length(yNew)
    loss = 1/n * HingeLoss()
    reg =  OneReg()
    w = proxgrad(loss, reg, x, yNew, maxiters=10)
    return w
end

hingeLoss_noreg_lasso (generic function with 1 method)

## L1 Loss

In [26]:
# l1loss
# function l1_quad(x, y)
#     yNew = toBool(y, 7200)
#     n = length(yNew)
#     loss = 1/n * L1Loss()
#     reg =  QuadReg()
#     w = proxgrad(loss, reg, x, yNew, maxiters=1000)
#     return w
# end

## L1 Loss with no regularization

In [27]:
# L1 loss and no regularization
# function l1_noreg(x, y)
#     yNew = toBool(y, 7200)
#     n = length(yNew)
#     loss = 1/n * L1Loss()
#     reg =  ZeroReg()
#     w = proxgrad(loss, reg, x, yNew, maxiters=1000)
#     return w
# end

## L1 Loss with L1 regularization

In [28]:
# logistic loss with l1 regularization
# function l1_l1(x, y)
#     yNew = toBool(y, 7200)
#     n = length(yNew)
#     loss = 1/n * L1Loss()
#     reg =  OneReg()
#     w = proxgrad(loss, reg, x, yNew, maxiters=100)
#     return w
# end

## Quantile Regression

In [29]:
# function quantReg(alpha, y, x)
#     n=length(y)
    
#     loss = 1/n * QuantileLoss(quantile = alpha)

#     lambda = 0
#     reg = lambda * QuadReg()
#     w = proxgrad(loss,reg, convert(Array{Float64,2}, x), y, maxiters=1000)
#     return w
# end

## Least Squares

In [30]:
# fit least squares now that we categorized the y values into being long or short 
# function least(x, y)
#     yNew = toBool(y, 7200)
#     n = length(yNew)
#     loss = 1/n * QuadLoss()
#     reg = ZeroReg()
#     w = proxgrad(loss, reg, x, yNew, maxiters=1000)
#     return w
# end

## Function Calls

In [59]:
w_logReg = logReg(trainX,train_y[:, 1])

840-element Array{Float64,1}:
 -1.44821525632343e-5  
 -9.765291102802224e-6 
 -2.5300766834747124e-6
 -9.858259305216664e-6 
  3.0697087895839945e-6
 -9.853911362049018e-6 
  1.4250242093473399e-5
  8.767476840950268e-6 
  1.3013035581227239e-5
  2.4030571866394157e-6
 -1.8206799233982068e-6
  5.66630550553124e-6  
 -7.310784077368963e-7 
  ⋮                    
 -1.4457311890304924e-5
  2.066155234780892e-5 
 -1.1971180156954124e-5
  3.059974902856385e-5 
 -6.641431171519243e-6 
 -6.177879001956588e-6 
 -5.180211562498428e-5 
 -0.003018843419626677 
 -1.27714954989696e-6  
  0.0014421692805488904
 -2.471102031974935e-6 
 -1.140544942768553e-6 

In [61]:
w_logReg_noreg = logReg_noreg(trainX,train_y[:, 1])

840-element Array{Float64,1}:
 -1.4680749538663505e-5
 -1.096557783961492e-5 
 -1.4427201008835414e-6
 -7.653166756427442e-6 
  6.993422112811768e-6 
 -3.2721638301163638e-6
  7.943073648249212e-6 
  8.931731317861632e-6 
  8.668435762547613e-6 
  7.753358088872167e-6 
 -7.631955685304123e-6 
  4.444373695595977e-6 
 -6.820880558109566e-7 
  ⋮                    
 -1.3731166484877738e-5
  2.4819673208104948e-5
 -1.0843841871484366e-5
  2.684293726649334e-5 
 -7.884670921060317e-6 
 -5.467863667998482e-6 
 -1.5188195492633868e-7
 -0.0024411127656772643
 -3.0439578134881897e-6
  0.001533588787387848 
 -2.782060378373802e-6 
 -9.119391250714032e-7 

In [83]:
w_log_l1 = log_l1(trainX,train_y[:, 1])

840-element Array{Float64,1}:
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  ⋮                     
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
  0.0                   
 -0.024678453125533063  
  0.0                   
 -0.00039163613599382623
  0.0                   
  0.0                   

In [26]:
w_hingeLoss = hingeLoss(trainX,train_y[:, 1])

840-element Array{Float64,1}:
 -0.00035760276225969254
 -0.00048302150557156544
  0.000272555691862118  
  0.00022435569532003628
 -0.00024947673810437547
  0.00030879179465916827
 -4.304570191964412e-5  
  0.00015318538187176546
  0.00029098008392009904
 -0.00010162475287627178
 -0.0002729737825630466 
  0.0002680907332686313 
  7.071127065054656e-6  
  ⋮                     
 -0.0004863989020651396 
 -0.0002497926757937229 
 -0.0004495905955721152 
 -0.00033823715452068446
 -0.00015914859632598446
  0.0008994609944653969 
  0.0004774320284963516 
 -0.002834156200320275  
 -9.493914920332666e-5  
  0.05353775313087843   
 -9.142032466465593e-5  
  1.0214137607289994e-5 

In [27]:
w_hingeLoss_noreg = hingeLoss_noreg(trainX,train_y[:, 1])

840-element Array{Float64,1}:
 -0.041705543420813805 
 -0.056331624438805565 
  0.03178268177870292  
  0.02618303751713205  
 -0.029096034232911166 
  0.036007271705112094 
 -0.00502231996995673  
  0.017861876500015278 
  0.033940137427752176 
 -0.01185372307387638  
 -0.031836222571695084 
  0.03129212465190199  
  0.0008255674168250395
  ⋮                    
 -0.05668967019606398  
 -0.029099142249500057 
 -0.05242420025382928  
 -0.039444165253888906 
 -0.01856421473481734  
  0.10488923866123624  
  0.056089280827385624 
 -0.2722376167151356   
 -0.011073111319989353 
  6.246952051549698    
 -0.010661903143192923 
  0.0012216618725680423

In [ ]:
# w_hinge_l1 = hinge_l1(trainX,train_y[:, 1])

In [ ]:
# w_l1_quad = l1_quad(trainX,train_y[:, 1])

In [ ]:
# w_l1_noreg = l1_noreg(trainX,train_y[:, 1])

In [ ]:
# w_l1_l1 = l1_l1(trainX,train_y[:, 1])

In [ ]:
# w_quantReg = quantReg(.9, train_y[:, 1], trainX)

In [ ]:
# w_least = least(trainX,train_y[:, 1])

In [28]:
w_weighthingeLoss = weighthingeLoss(trainX,train_y[:, 1])

840-element Array{Float64,1}:
 -0.00035760276225969254
 -0.00048302150557156544
  0.000272555691862118  
  0.00022435569532003628
 -0.00024947673810437547
  0.00030879179465916827
 -4.304570191964412e-5  
  0.00015318538187176546
  0.00029098008392009904
 -0.00010162475287627178
 -0.0002729737825630466 
  0.0002680907332686313 
  7.071127065054656e-6  
  ⋮                     
 -0.0004863989020651396 
 -0.0002497926757937229 
 -0.0004495905955721152 
 -0.00033823715452068446
 -0.00015914859632598446
  0.0008994609944653969 
  0.0004774320284963516 
 -0.002834156200320275  
 -9.493914920332666e-5  
  0.05353775313087843   
 -9.142032466465593e-5  
  1.0214137607289994e-5 

In [29]:
w_weighthinge_zero = weighthinge_zero(trainX,train_y[:, 1])  

840-element Array{Float64,1}:
   -0.047323011810365335
   -0.05959759443273398 
    0.016301984007494177
    0.013867978185954588
   -0.036411807019304965
    0.02000526949713918 
   -0.015538743350396289
    0.004242781625347068
    0.01898900933453773 
   -0.021423015156077668
   -0.03876007895881427 
    0.015994596674361542
    0.000150557061126162
    ⋮                   
   -0.06891122151962228 
   -0.044301415236374445
   -0.06548604837900227 
   -0.055082973669242974
   -0.035579561042524285
    0.07363494931245625 
   -1.7608401084010405  
 -258.9048834855722     
   -0.022224626953059656
   -1.8763393305229294  
   -0.011989193348723637
   -0.12965263140285038 

In [30]:
w_hingeLoss_noreg_lasso = hingeLoss_noreg_lasso(trainX,train_y[:, 1])

840-element Array{Float64,1}:
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     ⋮                 
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
    -2.5283047274917068
 -1781.5784004985178   
     0.0               
   -40.559680191709305 
     0.0               
     0.0               

In [31]:
w_weighthingeLoss_lasso = weighthingeLoss_lasso(trainX,train_y[:, 1])

840-element Array{Float64,1}:
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     ⋮                 
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
     0.0               
    -2.5283047274917068
 -1781.5784004985178   
     0.0               
   -40.559680191709305 
     0.0               
     0.0               

## Misclassification Rate

In [35]:
# calculates the misclassification rate of a model
function misclassification(X, y, w, cutoff)
    n = size(X,1)
    origY = toBool(y, 3600)
    newY = toBool(y, cutoff)
    mis = 0
    for i in 1:n
        if(origY[i] != newY[i])
            mis += 1/n
        end
    end
    return round(mis, digits=4)
end

misclassification (generic function with 1 method)

In [36]:
# test_y = vec(test_y)

In [42]:
# calculates the misclassification rate of a model
# function misclassification(X, y, w)
#     return (length(y) - dot(Int.(sign.(X*w)), y))/length(y)
# end

misclassification (generic function with 1 method)

In [78]:
misclassification(testX,test_y,w_logReg, .5)

0.0

In [79]:
misclassification(testX,test_y,w_logReg_noreg, .5)

0.0

In [84]:
misclassification(testX,test_y,w_log_l1, .5)

0.0

In [37]:
misclassification(testX,test_y,w_hingeLoss, 0)

0.0

In [38]:
misclassification(testX,test_y,w_hingeLoss_noreg, 0)

0.0

In [54]:
# misclassification(testX,test_y,w_l1_quad, .5)

In [55]:
# misclassification(testX,test_y,w_l1_noreg, .5)

In [56]:
# misclassification(testX,test_y,w_l1_l1)

In [100]:
# misclassification(Xtest,test_y,w_quantReg)

In [101]:
# misclassification1(Xtest,test_y,w_quantReg)

In [102]:
# misclassification(Xtest,test_y,w_least)

In [39]:
misclassification(testX,test_y,w_weighthingeLoss)

0.0

In [40]:
misclassification(testX,test_y,w_weighthinge_zero)

0.0

In [41]:
misclassification(testX,test_y,w_weighthingeLoss_lasso)

0.0

In [42]:
misclassification(testX,test_y,w_hingeLoss_noreg_lasso)

0.0